spring:
  application:
    name: TBK
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      db-type: postgresql
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/tbk
      username: postgres
      password: 123456
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/kotlin
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: 'user'
      paths-to-match: '/user/**'
      packages-to-scan: com.su.tbk
    - group: 'admin'
      paths-to-match: '/admin/**'
      packages-to-scan: com.su.tbk
knife4j:
  enable: true
  setting:
    language: zh-CN
    swaggerModelName: 实体类列表
  basic:
    enable: true
    username: su
    password: 123
server:
  port: 9527
